### ISSUE TITLE
[Init] 프로젝트 초기 세팅 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Tamagotchi#1]
## 📌  Feature Issue
프로젝트 초기 세팅을 진행합니다. 

## 📝  To-do
- [x] github 파일 추가
- [x] .gitignore 파일 추가
- [x] 프로젝트 추가
- [x] 프로젝트 초기 폴더링
