### ISSUE TITLE
[Feat] 설정 UI 구현

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Tamagotchi#4]
## 📌  Feature Issue
설정 UI를 구현합니다.

## 📝  To-do
- [x] UITableView로 전체 UI 구현
- [x] cell 구성
- [x] 각 cell 선택 시, 해당하는 설정 화면으로 이동 
- [x] 각 설정 UI 구현
