### ISSUE TITLE
[Fix] 전반적인 코드 수정 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Tamagotchi#7]
## 📌  Feature Issue
기간 내에 완벽히 구현하지 못한 기능을 수정합니다.

## 📝  To-do
- [x] 시작 화면 분기처리
- [x] 상세한 레이아웃 수정
- [x] 유저 디폴츠 수정
- [x] 화면 재사용
