### ISSUE TITLE
[Refactor] 피드백 반영 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Tamagotchi#8]
## 📌  Feature Issue
개별 피드백을 반영하여 코드를 전반적으로 수정합니다.

## 📝  To-do
- [x] 준비중인 다마고치 -> 토스트메시지 등과 같은 유저 인터랙션 추가
- [x] 필요 없는(= 사용하지 않는) 파일 삭제
- [x] 유저디폴츠 상수화 수정 (static var -> static let)
- [x] 유저디폴츠 
- [x] 설정 테이블 뷰 헤더 높이 수정 
- [x] 설정 뷰 셀 선택 시 동작 함수화
- [x] internal 접근 제어 생략
- [ ] 옵셔널체이닝 이슈 해결 
- [x] 중복되는 코드 정리 (비효율적인 코드 정리)
